# The URL the site will be built for
base_url = "https://looper.blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# TABI theme
theme = "tabi"
title = "Looper's Blog"
# TODO: 目前不支持，等待官方更新。
# default_language = "zh-Hans"

taxonomies = [{name = "tags", feed = true}]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
toc = true
skin = "blue"
stylesheets = ["css/custom.css"]

[search]
index_format = "elasticlunr_json" # Or the less efficient "elasticlunr_javascript".
include_title = true
include_description = true
include_path = true
include_content = true
